Add video transcript feature
apivideo/api.video-documentation pull request #417
Opened 2024-10-04 13:33 UTC by szekelyzol

Changes are for [this Asana task](https://app.asana.com/0/1205634133195403/1208447164598020).

**Summary:**

- added the new request and response attributes to the `/videos` endpoint **schemas** and **examples**
- created a Transcript guide that explains the usage and the supported languages
- crosslinked Transcript guide with Captions guide and API reference

2024-10-04 15:58 UTC, olivierapivideo approved these changes

2024-10-08 10:25 UTC, olivierapivideo requested changes

2024-10-08 10:25 UTC, olivierapivideo commented on openapi.yaml
> +        reanscript: true
typo here

2024-10-08 17:13 UTC, szekelyzol commented on openapi.yaml
> +        reanscript: true
Nice catch! Fixing...

2024-10-08 17:13 UTC, szekelyzol commented on openapi.yaml
> +          type: string
Thanks, good catch! Fixing...

2024-10-09 11:02 UTC, merged